### ISSUE TITLE
[bug]  Bots tend to not pick up neutral items

### ISSUE THREAD

**Issue by bluemoonhorse** [Yewchi/vulft#8]
**Describe the bug or unexpected behavior**
Neutral items are not switched for upgrades after the first item is obtained

**Can you cause the bug to happen by doing anything?**

**Optional:**
**Screenshots of match**
![image](https://user-images.githubusercontent.com/125678573/228204100-28d1d4cf-c7cc-4d00-a79c-4950423a76a0.png)
![image](https://user-images.githubusercontent.com/125678573/228204157-67ba6957-2c7a-442d-94f8-ac881a41c84b.png)

**What was the game clock? ( -1:30 to 0:00 to xx:xx )**

**Are you in an All Pick match, with 5 players vs 5 players, on Local Dev Script custom lobby?**
**If not, state the game settings for your match**
"Turbo"

**Console dump (best if you pause the match right when it happens)**
```
Copy and paste any console text here
```

**Comment by Yewchi** [comment]
Functionality for full takeover bots to send items to the neutral stash is not confirmed.

Turbo mode is also untested and the bots use the game clock for analytics.
